package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateMarkdownDocsStableAndComplete(t *testing.T) {
	out := t.TempDir()
	root := newRootCommand()

	if err := generateMarkdownDocs(root, out); err != nil {
		t.Fatalf("generateMarkdownDocs: %v", err)
	}

	rootDoc := readDoc(t, out, "confluence.md")
	if !strings.Contains(rootDoc, "# confluence") {
		t.Fatalf("root doc missing title:\n%s", rootDoc)
	}
	if !strings.Contains(rootDoc, "## Workflow") {
		t.Fatalf("root doc missing workflow section")
	}
	if !strings.Contains(rootDoc, "## Options") {
		t.Fatalf("root doc missing options section")
	}
	if strings.Contains(rootDoc, "Auto generated") || strings.Contains(rootDoc, "Generated by") {
		t.Fatalf("root doc contains generated timestamp/footer")
	}
	if strings.HasSuffix(rootDoc, "\n\n") {
		t.Fatalf("root doc has trailing blank line")
	}

	leafDoc := readDoc(t, out, "confluence_property_content_set.md")
	if !strings.Contains(leafDoc, "# confluence property content set") {
		t.Fatalf("leaf doc missing title:\n%s", leafDoc)
	}
	if !strings.Contains(leafDoc, "## Examples") {
		t.Fatalf("leaf doc missing examples")
	}
	if !strings.Contains(leafDoc, "--json") {
		t.Fatalf("leaf doc missing inherited global flags")
	}
	if strings.Contains(leafDoc, "Auto generated") || strings.Contains(leafDoc, "Generated by") {
		t.Fatalf("leaf doc contains generated timestamp/footer")
	}
	if strings.HasSuffix(leafDoc, "\n\n") {
		t.Fatalf("leaf doc has trailing blank line")
	}

	taskDoc := readDoc(t, out, "confluence_task_long_view.md")
	if !strings.Contains(taskDoc, "# confluence task long view") {
		t.Fatalf("nested task doc missing title")
	}
}

func TestDocsMarkdownCommandHelpAndOutput(t *testing.T) {
	help := captureHelp(t, []string{"docs", "markdown"})
	if !strings.Contains(help, "Examples:") {
		t.Fatalf("docs markdown --help missing examples:\n%s", help)
	}
	if !strings.Contains(help, "--out") {
		t.Fatalf("docs markdown --help missing --out flag:\n%s", help)
	}
}

func readDoc(t *testing.T, dir, name string) string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(dir, name))
	if err != nil {
		t.Fatalf("read %s: %v", name, err)
	}
	return string(data)
}
